name: Publish to npm

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, '[ Type ] NPM version update' ) && startsWith( github.head_ref, 'release/') && github.event.pull_request.merged == true
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Publish package to npm
        uses: Automattic/vip-actions/npm-publish@2e39f0da80dc446ab3180040691e83e41bc2450b
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_TRUSTED_PUBLISHING: 'true'
          node-version: 'lts/*'
