name: Publish to npm

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, '[ Type ] NPM version update' ) && startsWith( github.head_ref, 'release/') && github.event.pull_request.merged == true
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Publish package to npm
        uses: Automattic/vip-actions/npm-publish@7db404459133b50892861fd43a9d16e1129366cd
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_TRUSTED_PUBLISHING: 'true'
          node-version: 'lts/*'
